# Generated by Django 3.1.5 on 2021-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('prize', models.IntegerField()),
                ('model_year', models.CharField(max_length=4)),
                ('photo', models.ImageField(upload_to='itemImage')),
                ('description', models.TextField()),
                ('seller_id', models.IntegerField()),
                ('mo_no', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
