# Generated by Django 3.1.5 on 2021-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20210311_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='area',
            field=models.CharField(default='varachha', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='car', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=30),
        ),
    ]
