# Generated by Django 3.1.5 on 2021-03-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20210331_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='area',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(max_length=15),
        ),
    ]
